package io.github.andreabattaglia.fsm;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Mutable builder used to assemble an immutable {@link StateMachine}.
 *
 * <p>The builder is intentionally small and explicit. A valid state machine
 * requires one non-null initial state and zero or more transitions. Transitions
 * are keyed by the pair {@code (from, event)}, so adding two transitions with
 * the same source state and event is rejected immediately.</p>
 *
 * <p>The builder itself is not designed for concurrent use. Build the machine
 * during configuration or application startup, then share the resulting
 * immutable {@link StateMachine} wherever needed.</p>
 *
 * @param <S> the state type handled by the state machine
 * @param <E> the event type handled by the state machine
 * @param <C> the payload/context type passed by the caller when firing events
 */
public final class StateMachineBuilder<S, E, C> {

    private final Map<TransitionKey<S, E>, Transition<S, E, C>> transitions = new LinkedHashMap<>();
    private S initialState;

    StateMachineBuilder() {
    }

    /**
     * Configures the initial state metadata for the state machine.
     *
     * <p>The initial state is required before calling {@link #build()}. It is not
     * automatically used by {@link StateMachine#fire(Object, Object, Object)},
     * because the built state machine remains stateless. Callers may read it
     * through {@link StateMachine#initialState()} to initialize their own stored
     * workflow state.</p>
     *
     * @param initialState non-null initial state
     * @return this builder for fluent configuration
     * @throws NullPointerException when {@code initialState} is {@code null}
     */
    public StateMachineBuilder<S, E, C> initialState(S initialState) {
        this.initialState = Objects.requireNonNull(initialState, "initialState must not be null");
        return this;
    }

    /**
     * Adds a simple transition with an always-true guard and a no-op action.
     *
     * <p>This is the shortest form for transitions that are unconditional and do
     * not need side effects. It is equivalent to adding
     * {@link Transition#of(Object, Object, Object)}.</p>
     *
     * @param from source state
     * @param event triggering event
     * @param to destination state
     * @return this builder for fluent configuration
     * @throws NullPointerException when any transition component is {@code null}
     * @throws DuplicateTransitionException when a transition with the same
     *                                      source state and event already exists
     */
    public StateMachineBuilder<S, E, C> transition(S from, E event, S to) {
        return transition(Transition.of(from, event, to));
    }

    /**
     * Adds a transition with an explicit guard and action.
     *
     * <p>The guard is evaluated at runtime whenever the transition is selected.
     * The action is executed only after the guard returns {@code true}. Both
     * receive a {@link TransitionContext} containing the source state, event,
     * destination state, and runtime payload.</p>
     *
     * @param from source state
     * @param event triggering event
     * @param to destination state
     * @param guard predicate that must accept the transition
     * @param action side effect executed after guard acceptance
     * @return this builder for fluent configuration
     * @throws NullPointerException when any transition component is {@code null}
     * @throws DuplicateTransitionException when a transition with the same
     *                                      source state and event already exists
     */
    public StateMachineBuilder<S, E, C> transition(
            S from,
            E event,
            S to,
            Guard<S, E, C> guard,
            Action<S, E, C> action
    ) {
        return transition(Transition.of(from, event, to, guard, action));
    }

    /**
     * Adds a pre-built transition.
     *
     * <p>This overload is useful when transitions are assembled elsewhere, read
     * from configuration, generated by tests, or reused across several builder
     * setup paths.</p>
     *
     * @param transition transition to add
     * @return this builder for fluent configuration
     * @throws NullPointerException when {@code transition} is {@code null}
     * @throws DuplicateTransitionException when a transition with the same
     *                                      source state and event already exists
     */
    public StateMachineBuilder<S, E, C> transition(Transition<S, E, C> transition) {
        Objects.requireNonNull(transition, "transition must not be null");
        var key = new TransitionKey<>(transition.from(), transition.event());
        if (transitions.containsKey(key)) {
            throw new DuplicateTransitionException(transition.from(), transition.event());
        }
        transitions.put(key, transition);
        return this;
    }

    /**
     * Builds an immutable state machine from the current builder content.
     *
     * <p>The returned state machine contains an immutable snapshot of the
     * configured transitions. Subsequent builder changes, if any, do not affect
     * state machines that have already been built.</p>
     *
     * @return immutable state machine
     * @throws IllegalStateException when no initial state has been configured
     */
    public StateMachine<S, E, C> build() {
        if (initialState == null) {
            throw new IllegalStateException("initialState must be configured");
        }
        return new StateMachine<>(new StateMachineDefinition<>(initialState, transitions));
    }
}
